site_name: Ouw Productions frameworks
extra:
  head:
    - '<meta property="og:title" content="Introduction - Ouw Productions frameworks">'
    - '<meta property="og:description" content="Documentation for Ouw Productions frameworks">'
    - '<meta property="og:image" content="URL_to_an_image.png">'
    - '<meta property="og:url" content="https://11ouw0pp11.github.io/Ouw0pp.github.io/">'
    - '<meta property="og:type" content="website">'
plugins:
  - search
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: |
  &copy; 2024 <a href="https://github.com/11Ouw0pp11" target="_blank" rel="noopener">Ouw0pp</a>
